remote_theme: "mmistakes/minimal-mistakes@4.27.3"

minimal_mistakes_skin: "air"

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

locale: "en-US"
title: "Nathaniel Bonacci"
description: "Mechanical & Computer Engineering | Simulation & Robotics"
url: "https://bonaccin.github.io"
baseurl: ""

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

author:
  name: "Nathaniel Bonacci"
  # avatar: "/assets/images/bio-photo.jpg"
  bio: "Mechanical & Computer Engineering | Simulation & Robotics"
  location: "Hillsborough, NJ"
  links:
    - label: "Made Mistakes"
      icon: "fas fa-fw fa-link"
      url: "https://mademistakes.com"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/mmistakes"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/mmistakes"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/mmistakes"
